### ISSUE TITLE
Classifying Malware using Import API and Fuzzy Hashing

### ISSUE THREAD

**Issue by rot0xd** [tnvo/mal-reading-notes#1]
**Paper**:  Classifying Malware using Import API and Fuzzy Hashing 
**Author**: impfuzzy
**Published**: May 25, 2016.
**Publisher**: JPCERT/CC. 
**Link**: http://blog.jpcert.or.jp/2016/05/classifying-mal-a988.html

**Comment by tnvo** [comment]
https://github.com/tnvo/mal-reading-notes/blob/master/tnvo.md#classifying-malware-using-import-api-and-fuzzy-hashing-impfuzzy
