### ISSUE TITLE
BinGold: Towards robust binary analysis by extracting the semantics of binary code as semantic flow graphs (SFGs)

### ISSUE THREAD

**Issue by rot0xd** [tnvo/mal-reading-notes#2]
**Paper**:  BinGold: Towards robust binary analysis by extracting the semantics of binary code as semantic flow graphs (SFGs)
**Author**: Saed Alrabaee, Lingyu Wang, and Mourad Debbabi
**Published**: 2016
**Publisher**: DFRWS USA 
**Link**: https://www.sciencedirect.com/science/article/pii/S1742287616300330

**Comment by tnvo** [comment]
https://github.com/tnvo/mal-reading-notes/blob/master/tnvo.md#bingold-towards-robust-binary-analysis-by-extracting-the-semantics-of-binary-code-as-semantic-flow-graphs-sfgs
