### ISSUE TITLE
The Kings In Your Castle Part 2 – Dataset and feature extraction

### ISSUE THREAD

**Issue by rot0xd** [tnvo/mal-reading-notes#3]
**Paper**: The Kings In Your Castle Part 2 – Dataset and feature extraction
**Author**: Marion Marschalek
**Published**: October 31, 2016
**Publisher**: cyber.wtf
**Link**: https://cyber.wtf/2016/10/31/the-kings-in-your-castle-part-2-dataset-and-feature-extraction/

**Comment by tnvo** [comment]
https://github.com/tnvo/mal-reading-notes/blob/master/tnvo.md#the-kings-in-your-castle-part-2--dataset-and-feature-extraction
