### ISSUE TITLE
AVClass: A tool for Massive Malware Labeling

### ISSUE THREAD

**Issue by rot0xd** [tnvo/mal-reading-notes#8]
**Paper**: AVClass: A tool for Massive Malware Labeling
**Author**: Marcos Sebastián, Richard Rivera, Platon Kotzias, and Juan Caballero
**Published**: September 2016
**Publisher**: International Symposium on Research in Attacks, Intrusions and Defenses
**Link**: https://software.imdea.org/~juanca/papers/avclass_raid16.pdf

**Comment by tnvo** [comment]
https://github.com/tnvo/mal-reading-notes/blob/master/tnvo.md#avclass-a-tool-for-massive-malware-labeling
