### ISSUE TITLE
Mal-Xtract: Hidden Code Extraction using Memory Analysis

### ISSUE THREAD

**Issue by rot0xd** [tnvo/mal-reading-notes#9]
**Paper**: Mal-Xtract: Hidden Code Extraction using Memory Analysis
**Author**: Charles Lim, Yohanes Syailendra Kotualubun, Suryadi, and Kalamullah Ramli
**Published**: 2017
**Publisher**: Journal of Physics: Conference Series 801 012058
**Link**: https://www.researchgate.net/publication/315592647_Mal-Xtract_Hidden_Code_Extraction_using_Memory_Analysis

**Comment by tnvo** [comment]
Found a typo in this paper in the abstract. There're 2 "to" :D

**Comment by tnvo** [comment]
https://github.com/tnvo/mal-reading-notes/blob/master/tnvo.md#mal-xtract-hidden-code-extractionusing-memory-analysis
